#!/bin/bash
for i in 1 3 5 7 10
do
    echo $i
    # log norm
    python word2vec.py newText2LimitSize word_embeddingNeg1Epoch${i} 1 $i 0 log
    python word2vec.py newText2LimitSize word_embeddingNeg1BoostEpoch${i} 25 $i 0 log
    python generateStatsL2Window.py word_embeddingNeg1Epoch${i} statsOutput/statslogNeg1Epoch${i} vocab.txt word_embeddingNeg1Epoch${i}_2 reslogNeg
    python generateStatsL2Window.py word_embeddingNeg1BoostEpoch${i} statsOutput/statslogNeg1BoostEpoch${i} vocab.txt word_embeddingNeg1BoostEpoch${i}_2 reslogBoost



    # l2 norm
    python word2vec.py newText2LimitSize word_embeddingNeg1Boostl2Epoch${i} 25 $i 0 l2
    python word2vec.py newText2LimitSize word_embeddingNeg1l2Epoch${i} 1 $i 0 l2
    python generateStatsL2Window.py word_embeddingNeg1Boostl2Epoch${i} statsOutput/statsl2Neg1BoostEpoch${i} vocab.txt word_embeddingNeg1Boostl2Epoch${i}_2 resl2Boost
    python generateStatsL2Window.py word_embeddingNeg1l2Epoch${i} statsOutput/statsl2Neg1Epoch${i} vocab.txt word_embeddingNeg1l2Epoch${i}_2 resl2Neg


    # l1 norm
    python word2vec.py newText2LimitSize word_embeddingNeg1Boostl1Epoch${i} 25 $i 0 l1
    python word2vec.py newText2LimitSize word_embeddingNeg1l1Epoch${i} 1 $i 0 l1
    python generateStatsL1Window.py word_embeddingNeg1Boostl1Epoch${i} statsOutput/statsl1Neg1BoostEpoch${i} vocab.txt word_embeddingNeg1Boostl1Epoch${i}_2 resl1Boost
    python generateStatsL1Window.py word_embeddingNeg1l1Epoch${i} statsOutput/statsl1Neg1Epoch${i} vocab.txt word_embeddingNeg1l1Epoch${i}_2 resl1Neg
done
