#!/bin/bash
for i in 1 3 5 7 10 1 3 5 7 10
do
    echo $i


    # before running, please change the word2vec.py line 76 to self.data.get_neg_v_neg_sampling(pos_pairs, 15)
    # l2 norm
    python word2vec.py newText2LimitSize word_embeddingNeg15l2EpochMultiRun${i} 1 $i 0 l2
    python generateStatsL2Window.py word_embeddingNeg15l2EpochMultiRun${i} statsOutput/statsl2Neg15EpochMultiRun${i} vocab.txt word_embeddingNeg15l2EpochMultiRun${i}_2 resMultiRunl2Neg15


done
