#!/bin/bash
#for i in 1 3 5 7 10 1 3 5 7 10
for i in 10
do
    echo $i



    # l2 norm
    python word2vecCluster.py newText2LimitSize word_embeddingPairs${i} 3 $i 0 l2
    #python word2vec.py newText2LimitSize word_embeddingNeg5l2EpochMultiRun${i} 1 $i 0 l2
    #python word2vec.py newText2LimitSize word_embeddingNoNegl2EpochMultiRun${i} 1 $i 1 l2
    python generateStatsL2Window.py word_embeddingPairs${i} statsOutput/statsl2Pairs${i} vocab.txt word_embeddingPairs${i}_2 resPairs


done
