#!/bin/bash
for i in 1 3 5 7 10 1 3 5 7 10
do
    echo $i



    # l2 norm
    python word2vec.py newText2LimitSize word_embeddingNeg5Boostl2EpochMultiRun${i} 3 $i 0 l2
    python word2vec.py newText2LimitSize word_embeddingNeg5l2EpochMultiRun${i} 1 $i 0 l2
#    python word2vec.py newText2LimitSize word_embeddingNoNegl2EpochMultiRun${i} 1 $i 1 l2
    python generateStatsL2Window.py word_embeddingNeg5Boostl2EpochMultiRun${i} statsOutput/statsl2Neg5BoostEpochMultiRun${i} vocab.txt word_embeddingNeg5Boostl2EpochMultiRun${i}_2 resMultiRunl2Boost
    python generateStatsL2Window.py word_embeddingNeg5l2EpochMultiRun${i} statsOutput/statsl2Neg5EpochMultiRun${i} vocab.txt word_embeddingNeg5l2EpochMultiRun${i}_2 resMultiRunl2Neg
#    python generateStatsL2Window.py word_embeddingNoNegl2EpochMultiRun${i} statsOutput/statsl2NoNegEpochMultiRun${i} vocab.txt word_embeddingNoNegl2EpochMultiRun${i}_2 resMultiRunl2NoNeg


done
