#!/bin/bash

for j in 5 10 15 20 50 100 400 600 1000 # different boosting factor
do
    i=5 # 5 epochs
    echo $i
    # log norm

    python word2vec.py newText2LimitSize word_embeddingNeg5Boost${j}Epoch${i}Batch5 $j $i 0 log
    python generateStatsL2Window.py word_embeddingNeg5Boost${j}Epoch${i}Batch5 statsOutput/statslogNeg5Boost${j}Epoch${i}Batch5 vocab.txt word_embeddingNeg5Boost${j}Epoch${i}Batch5_2 reslogBoost



done
