#!/bin/bash
for i in 1 3 5 7 10
do
    echo $i
    # log norm
    python word2vec.py newText2LimitSize word_embeddingNeg5Epoch${i} 1 $i 0 log
    python word2vec.py newText2LimitSize word_embeddingNeg5BoostEpoch${i} 3 $i 0 log
    python word2vec.py newText2LimitSize word_embeddingNoNegEpoch${i} 1 $i 1 log
    python generateStatsL2Window.py word_embeddingNeg5Epoch${i} statsOutput/statslogNeg5Epoch${i} vocab.txt word_embeddingNeg5Epoch${i}_2 reslogNeg
    python generateStatsL2Window.py word_embeddingNeg5BoostEpoch${i} statsOutput/statslogNeg5BoostEpoch${i} vocab.txt word_embeddingNeg5BoostEpoch${i}_2 reslogBoost
    python generateStatsL2Window.py word_embeddingNoNegEpoch${i} statsOutput/statslogNoNegEpoch${i} vocab.txt word_embeddingNoNegEpoch${i}_2 reslogNoNeg



    # l2 norm
    python word2vec.py newText2LimitSize word_embeddingNeg5Boostl2Epoch${i} 3 $i 0 l2
    python word2vec.py newText2LimitSize word_embeddingNeg5l2Epoch${i} 1 $i 0 l2
    python word2vec.py newText2LimitSize word_embeddingNoNegl2Epoch${i} 1 $i 1 l2
    python generateStatsL2Window.py word_embeddingNeg5Boostl2Epoch${i} statsOutput/statsl2Neg5BoostEpoch${i} vocab.txt word_embeddingNeg5Boostl2Epoch${i}_2 resl2Boost
    python generateStatsL2Window.py word_embeddingNeg5l2Epoch${i} statsOutput/statsl2Neg5Epoch${i} vocab.txt word_embeddingNeg5l2Epoch${i}_2 resl2Neg
    python generateStatsL2Window.py word_embeddingNoNegl2Epoch${i} statsOutput/statsl2NoNegEpoch${i} vocab.txt word_embeddingNoNegl2Epoch${i}_2 resl2NoNeg


    # l1 norm
    python word2vec.py newText2LimitSize word_embeddingNeg5Boostl1Epoch${i} 3 $i 0 l1
    python word2vec.py newText2LimitSize word_embeddingNeg5l1Epoch${i} 1 $i 0 l1
    python word2vec.py newText2LimitSize word_embeddingNoNegl1Epoch${i} 1 $i 1 l1
    python generateStatsL1Window.py word_embeddingNeg5Boostl1Epoch${i} statsOutput/statsl1Neg5BoostEpoch${i} vocab.txt word_embeddingNeg5Boostl1Epoch${i}_2 resl1Boost
    python generateStatsL1Window.py word_embeddingNeg5l1Epoch${i} statsOutput/statsl1Neg5Epoch${i} vocab.txt word_embeddingNeg5l1Epoch${i}_2 resl1Neg
    python generateStatsL1Window.py word_embeddingNoNegl1Epoch${i} statsOutput/statsl1NoNegEpoch${i} vocab.txt word_embeddingNoNegl1Epoch${i}_2 resl1NoNeg
done
