#!/bin/bash
for i in 1 3 5 7 10
do
    echo $i
    # log norm
    python word2vec.py newText2LimitSize word_embeddingNeg25Epoch${i} 1 $i 0 log
    python generateStatsL2Window.py word_embeddingNeg25Epoch${i} statsOutput/statslogNeg25Epoch${i} vocab.txt word_embeddingNeg25Epoch${i}_2 reslogNeg



    # l2 norm
    python word2vec.py newText2LimitSize word_embeddingNeg25l2Epoch${i} 1 $i 0 l2
    python generateStatsL2Window.py word_embeddingNeg25l2Epoch${i} statsOutput/statsl2Neg25Epoch${i} vocab.txt word_embeddingNeg25l2Epoch${i}_2 resl2Neg


    # l1 norm
    python word2vec.py newText2LimitSize word_embeddingNeg25l1Epoch${i} 1 $i 0 l1
    python generateStatsL1Window.py word_embeddingNeg25l1Epoch${i} statsOutput/statsl1Neg25Epoch${i} vocab.txt word_embeddingNeg25l1Epoch${i}_2 resl1Neg
done
