#!/bin/bash
for i in 1 3 5 7 10
do
        loss="log" # can only be L2, L1, log For L2 and log, change to generateStatsL2. Otherwise, generateStatsL1.
        python cbow_model.py $i 500 "embNeg5${loss}Epoch${i}" "embNeg5${loss}Epoch${i}_2" $loss
        python generateStatsL2.py "emb/embNeg5${loss}Epoch${i}" "outputStats/logNeg5${loss}Epoch${i}" vocab.txt "emb/embNeg5${loss}Epoch${i}_2" "res${loss}"
        python cbow_model.py $i 500 "embNeg5${loss}Epoch${i}Boost3" "embNeg5${loss}Epoch${i}Boost3_2" $loss 3
        python generateStatsL2.py "emb/embNeg5${loss}Epoch${i}Boost3" "outputStats/logNeg5${loss}Epoch${i}Boost3" vocab.txt "emb/embNeg5${loss}Epoch${i}Boost3_2" "resBoost${loss}"
done
